general:
  basemodel: "dbmdz/german-gpt2"
dataset:
  train_path: "/content/data/turn_pairs_train.txt"
  dev_path: "/content/data/turn_pairs_dev.txt"
train:
  epochs: 10
  save_steps: 10000
  save_total_limit: 3
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  output_dir: "model"
  use_fast_tokenizer: False